database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  # jdbc:h2:mem:btp - mem for in memory database otherwise it will be an embedded database file located at the url
  url: jdbc:h2:./target/btp

server: 
  adminContextPath: /
  applicationContextPath: / 
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  rootPath: /api/ # the application path is moved to a sub-url so that an webpage (asset) can be served via the root
  

logging:
  level: INFO
  
  loggers:
    org.hibernate.SQL:
      level: DEBUG
    
  appenders:
     - type: console
     - type: file
       threshold: INFO
       logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
       currentLogFilename: /tmp/application.log
       archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
       archivedFileCount: 7
       timeZone: UTC
       maxFileSize: 10MB

# assets:
  # overrides:
    # /: src/main/resources/webContent/
    #  mappings:
    # /webContent: /
    # Override requests to /${1} to instead look in 
    # ${working directory}/src/main/resources/webContent/${1}  